version: '3'

services:
  db:
    container_name: pg_container
    image: postgres
    env_file:
      - postgres.env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    env_file:
      - pgadmin.env
    restart: always
    ports:
      - '5050:80'
  frontend:
    container_name: app
    ports:
      - '8080:8080'
    build:
      context: ./